apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-veeranna
  labels:
    app: spring-boot-app-veeranna
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app-veeranna
  template:
    metadata:
      labels:
        app: spring-boot-app-veeranna
    spec:
      containers:
      - name: spring-boot-app-veeranna
        image: veerannadoc/argocd:11
        ports:
        - containerPort: 8080
